Repository nasa/FM, pull requests merged in 2022-06, with the labels that each got.

#28 Fix #4 #20, Add missing rationale and allow for multiple command counters in requirements
  docs/fm_FunctionalRequirements.csv
Labels: CCB:Approved

#30 Fix #29, Remove CFE_PSP_MemSet use on RAM
  fsw/src/fm_app.c
  fsw/src/fm_child.c
  fsw/src/fm_cmd_utils.c
  fsw/src/fm_cmds.c
  unit-test/fm_child_tests.c
  unit-test/fm_cmd_utils_tests.c
  unit-test/fm_tbl_tests.c
  unit-test/utilities/fm_test_utils.c
Labels: CCB:Approved

#32 Fix #31, Updates CLA information for Apache 2.0
  .github/pull_request_template.md
  CONTRIBUTING.md
  docs/Corp_CLA_FM_260.pdf
  docs/Indv_CLA_FM_260.pdf
Labels: docs, CCB:Approved

#33 Fix #17, update code coverage for fm_cmd_utils.c
  unit-test/fm_cmd_utils_tests.c
Labels: CCB:Approved

#26 Fix #25, Added codeql-build.yml
  .github/workflows/codeql-build.yml
Labels: CCB:Approved, dependency

#35 Part #17, update code coverage
  unit-test/fm_child_tests.c
  unit-test/fm_cmds_tests.c
Labels: coverage, unit-test, CCB:Approved

#38 Fix #36, Remove redundant conditional to support full coverage
  fsw/src/fm_child.c
Labels: CCB:Approved
